name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: Dockerfile

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
